[project]
name = "cefi-data-portal-mcp"
version = "0.1.0"
description = "The MCP server for the CEFI Data Portal"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.1",
]
